### ISSUE TITLE
the queryInput widget skips inputs with empty type attribute

### ISSUE THREAD

**Issue by JoeZ99** [doofinder/js-doofinder#144]
@carlosescri 
this is code from the `queryInput` widget

```coffee
  setElement: (element) ->
    @element = ($ element).filter [
      'input:not([type])',
      'input[type="text"]',
      'input[type="search"]',
      'textarea'
    ].join ","
```

https://idoctor.es/# has a searchbox like

```html
<input type="" name="" value="Ej: Consulta Traumatología Madrid" size="35px" style="size: 500px; float: left; height: 50px; border-radius: 5px; font-size: 18px;" onclick="if(this.value=='Ej: Consulta Traumatología Madrid') this.value=''" onblur="if(this.value=='') this.value=''">
```

with has an empty value as its `type` attribute. 

Classic layer doesn't work because queryinput filters out that kind of input.

Do we want this? if so, Is it on the doc??

**Comment by carlosescri** [comment]
@JoeZ99, to be sure we're talking about the same, the `[type]` selector matches those elements with a `type` attribute, so `input:not([type])` should match those elements with no `type` attribute. In HTML, inputs with no `type` attribute are considered as of type `text` by default.

In this case, the problem is that the search input has a `type` attribute with no value, which is an edge case and it's not valid HTML:

![image](https://user-images.githubusercontent.com/482075/44862345-c8398300-ac7a-11e8-992f-8d30ffda1855.png)

It's not a bug but, as we're not judging the user, this issue may make sense and we could add inputs with empty types to the set of matched elements.

**Comment by JoeZ99** [comment]
That's exactly what I meant: empty type attributes which most likely are bad html but bad html has never stopped the user before !
Or we could just be aware of this and let the user know if that ever happen, but I'm afraid is a tricky "bug" to catch and can make some desk guy spend tons of time trying to solve this...

**Comment by JoeZ99** [comment]
anyway, it's up to you to mark this as a "thing to do" or close it for good.

**Comment by carlosescri** [comment]
After a bit of thinking...

If the user puts:

```html
<input type="pepito">
```

The browser may accept it but it's also invalid HTML.

The same with:

```html
<input type="">
<input type=" ">
<input type="  ">
<input type="   ">
```

If we add the case for an empty `type` attribute, we're solving just one possible error, you're not ensuring that you will make disappear a lot of support cases.

I think the user should fix the input markup in this case.

**Comment by carlosescri** [comment]
(And in this case, seems that a lazy programmer hit the <kbd>tab</kbd> key after typing `input` and forgot the value for `type` because the `name` attribute is empty too.)
